### ISSUE TITLE
Not Loading, Console Error

### ISSUE THREAD

**Issue by elouangrimm** [aladinyo/ChatPlus#2]
The page keeps loading and the console keeps repeating this error:
```
content_script.js:1 Uncaught Error: Extension context invalidated.
    at M (content_script.js:1:3252)
    at HTMLDocument.<anonymous> (content_script.js:1:2063)
```
Thank you! I would love this to work.

**Comment by elouangrimm** [comment]
Sorry I think this error is fine, it's working now.
